services:
  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "4000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/logs:/app/logs

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "8081:80"
    depends_on:
      - backend

  postgres:
    image: postgres:18-alpine
    container_name: database-container
    environment:
      POSTGRES_DB: kupipodariday
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student -d myapp"]
      interval: 10s
      timeout: 7s
      retries: 7
    volumes:
      - ./postgres-data:/app/postgreqsl/data

volumes:
  pgdata: